name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p binary
      working-directory: .
    - name: make i286
      run: make -f Makefile.mingw i286
      working-directory: ./source
    - name: make i386
      run: make -f Makefile.mingw i386
      working-directory: ./source
    - name: make i486
      run: make -f Makefile.mingw i486
      working-directory: ./source
    - uses: actions/upload-artifact@master
      with:
        name: mingw
        path: ./binary

